create database orders;
USE ORDERS;

SELECT * FROM ORDER_TABLE;
describe order_table;

ALTER TABLE order_table
MODIFY order_id INT,
MODIFY ORDER_DATE date,
MODIFY POSTAL_CODE INT,
MODIFY QUANTITY INT;

#1. Find first top 10 highest revenue generating products
SELECT PRODUCT_ID, ROUND(SUM(SALE_PRICE), 2) AS 'Revenue' 
FROM ORDER_TABLE group by PRODUCT_ID order by 2 DESC LIMIT 10;

#2. Top 5 highest selling products in each region
WITH ORDER_CTE AS 
(SELECT REGION, PRODUCT_ID, SUM(SALE_PRICE) AS 'SALES' FROM ORDER_TABLE group by REGION, PRODUCT_ID)
SELECT * FROM 
(SELECT *, row_number() OVER(partition by REGION order by SALES DESC) AS RN FROM ORDER_CTE) AS T
WHERE RN<=5;

#3. Find month over month growth comparison for 2022 and 2023
WITH CTE AS
(SELECT YEAR(ORDER_DATE) AS ORDER_YEAR, MONTH(ORDER_DATE) AS ORDER_MONTH, ROUND(SUM(SALE_PRICE), 2) AS SALES 
FROM ORDER_TABLE 
group by YEAR(ORDER_DATE), MONTH(ORDER_DATE)
order by YEAR(ORDER_DATE), MONTH(ORDER_DATE))
SELECT ORDER_MONTH,
SUM(CASE WHEN ORDER_YEAR=2022 THEN SALES ELSE 0 END) AS SALES_2022,
SUM(CASE WHEN ORDER_YEAR=2023 THEN SALES ELSE 0 END) AS SALES_2023 FROM CTE
group by ORDER_MONTH
order by ORDER_MONTH;

#4. For each category which month had highest sales
WITH CTE AS 
(SELECT CATEGORY, EXTRACT(YEAR_MONTH FROM ORDER_DATE) AS 'yy_mm', ROUND(SUM(SALE_PRICE),2) AS SALES
 FROM ORDER_TABLE
 group by CATEGORY, EXTRACT(YEAR_MONTH FROM ORDER_DATE))
 SELECT * FROM
 (SELECT *, dense_rank() OVER(partition by CATEGORY order by SALES DESC) AS RK FROM CTE) AS T1
 WHERE RK = 1;

#5. which sub category had highest growth by SALES in 2023 compare to 2022
WITH CTE1 AS
(SELECT SUB_CATEGORY, YEAR(ORDER_DATE) AS ORDER_YEAR, ROUND(SUM(SALE_PRICE), 2) AS SALES
FROM ORDER_TABLE group by 1, 2),
CTE2 AS
(SELECT SUB_CATEGORY,
SUM(CASE WHEN ORDER_YEAR=2022 THEN SALES ELSE 0 END) AS SALE_2022,
SUM(CASE WHEN ORDER_YEAR=2023 THEN SALES ELSE 0 END) AS SALE_2023 FROM CTE1
group by SUB_CATEGORY
)
SELECT *, ROUND((SALE_2023 - SALE_2022),2) AS GROWTH, ROUND(((SALE_2023 - SALE_2022)*100)/SALE_2022,2) AS PER_GROWTH
FROM CTE2 order by 4 DESC;

SELECT * FROM ORDER_TABLE;

#6. Find monthly sales trend
SELECT YEAR(ORDER_DATE) AS ORDER_YEAR, MONTH(ORDER_DATE) AS ORDER_MONTH, ROUND(SUM(SALE_PRICE), 2) AS SALE
 FROM ORDER_TABLE group by 1,2 order by 3 DESC;
 
#7. Total Sales
SELECT SUM(SALE_PRICE)
 FROM ORDER_TABLE; 
 
 
#8. Revenue vs profit for each category
SELECT CATEGORY, ROUND(SUM(SALE_PRICE), 2) AS 'TOTAL_REVENUE', ROUND(SUM(PROFIT),2) AS 'TOTAL_PROFIT',
ROUND(SUM(PROFIT)*100/SUM(SALE_PRICE),2) AS '%_PROFIT'
FROM ORDER_TABLE group by 1;

#9. Revenue vs profit for each city
SELECT City, ROUND(SUM(SALE_PRICE), 2) AS 'TOTAL_REVENUE', ROUND(SUM(PROFIT),2) AS 'TOTAL_PROFIT',
ROUND(SUM(PROFIT)*100/SUM(SALE_PRICE),2) AS '%_PROFIT'
FROM ORDER_TABLE group by 1 order by 2 desc;

#10. Revenue vs profit for each state
SELECT State, ROUND(SUM(SALE_PRICE), 2) AS 'TOTAL_REVENUE', ROUND(SUM(PROFIT),2) AS 'TOTAL_PROFIT',
ROUND(SUM(PROFIT)*100/SUM(SALE_PRICE),2) AS '%_PROFIT'
FROM ORDER_TABLE group by 1 order by 2 desc;

#10. Revenue vs profit for each Region
SELECT Region, ROUND(SUM(SALE_PRICE), 2) AS 'TOTAL_REVENUE', ROUND(SUM(PROFIT),2) AS 'TOTAL_PROFIT',
ROUND(SUM(PROFIT)*100/SUM(SALE_PRICE),2) AS '%_PROFIT'
FROM ORDER_TABLE group by 1 order by 2 desc;

#11. Shipment mode
SELECT SHIP_MODE, COUNT(*) FROM ORDER_TABLE group by 1;

#12. Customer type
SELECT SEGMENT, COUNT(*) FROM ORDER_TABLE group by 1;

#13. Revenue vs profit for each SEGMENT
SELECT SEGMENT, ROUND(SUM(SALE_PRICE), 2) AS 'TOTAL_REVENUE', ROUND(SUM(PROFIT),2) AS 'TOTAL_PROFIT',
ROUND(SUM(PROFIT)*100/SUM(SALE_PRICE),2) AS '%_PROFIT'
FROM ORDER_TABLE group by 1 order by 2 desc;




